config/routes.rb
Rails.application.routes.draw do
  root 'rooms#index'

  resources :rooms do
    post :reaction
    resources :topics do
      resources :messages do
        post :like
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :topic

  # Unable to set dynamic target via broadcasts_to
  # This will append the message to the correct topic
  after_create_commit -> { broadcast_append_to room, target: broadcast_target }
  # Default is based on pluralized class name and id
  after_update_commit -> { broadcast_replace_to room }
  # Does not support setting a target
  after_destroy_commit -> { broadcast_remove_to room }

  def room
    topic.room
  end

  def broadcast_target
    topic.snakecase
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]
  before_action :set_topic, only: %i[ new edit create update destroy ]
  before_action :set_room, only: %i[ new edit create update destroy ]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)
    @message.topic = @topic

    respond_to do |format|
      if @message.save
        format.turbo_stream
        format.html { redirect_to @room, notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @room, notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to @room, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def like
    message = Message.find(params[:message_id])
    message.increment! :likes
    message.touch # increment does not trigger callbacks

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(:message, partial: "message", locals: {message: message})
      end
    end


  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = Message.find(params[:id])
  end

  def set_topic
    @topic = Topic.find(params[:topic_id])
  end

  def set_room
    @room = Room.find(params[:room_id])
  end

  # Only allow a list of trusted parameters through.
  def message_params
    params.require(:message).permit(:body)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: [@room, @topic, message], data: {controller: "reset-form", action: "turbo:submit-end->reset-form#reset"}) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <% if @topic.name == 'Shoutouts' %>
      <a target="_blank" href='https://federate.f5.com/f5-w-68747470733a2f2f696e7472616e65742d617070732e66356e65742e636f6d$$/Recognition/shout-out' class='btn'>
        <i class='fas fa-trophy'></i> F5 Shoutout
      </a>
    <% end %>
    <%= form.button type: :submit, class: 'btn' do %>
      <i class='fas fa-plus'></i> Comment
    <% end %>
  </div>

<% end %>

app/views/messages/_message.html.erb
<%= turbo_frame_tag(dom_id(message)) do %>
  <div class='message speech-bubble'>
    <div class='delete'>
      <%= button_to room_topic_message_path(message.topic.room, message.topic, message), method: :delete, class: "btn btn-red" do %>
        <i class='fas fa-times'></i>
      <% end %>
    </div>

    <div class='actions'>
      <%= link_to edit_room_topic_message_path(message.topic.room, message.topic, message), class: "btn btn-green" do %>
        <i class='fas fa-edit'></i>
      <% end %>

      <%= button_to room_topic_message_like_path(message.topic.room, message.topic, message), class: "btn btn-like" do %>
        <i class='fas fa-inverse fa-thumbs-up'></i>
        <%= message.likes || 0 %>
      <% end %>
    </div>



    <div class='content'>
      <%= message.body %>
    </div>



  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= turbo_frame_tag(dom_id(@message)) do %>
  <%= render 'form', message: @message %>
<% end %>

<%= link_to 'Back', room_path(@room) %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Topic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.body %></td>
        <td><%= message.topic_id %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= turbo_frame_tag "new_message", target: "_top" do %>
  <%= render 'form', message: @message %>
<% end %>

<%= link_to 'Back', room_path(@room) %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @message.topic_name %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>