config/routes.rb
Rails.application.routes.draw do
  root 'rooms#index'

  resources :rooms do
    post :reaction
    resources :topics do
      resources :messages do
        post :like
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  after_update_commit -> { broadcast_replace_to self, target: "reactions", partial: "rooms/reactions" }

  has_many :topics, dependent: :delete_all
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        @room.topics << Topic.create(name: "Went Well")
        @room.topics << Topic.create(name: "Needs Improvement")
        @room.topics << Topic.create(name: "Shoutouts")

        format.html { redirect_to rooms_url, notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def reaction
    reaction = params[:reaction].pluralize
    room = Room.find(params[:room_id])
    room.increment! reaction
    room.touch # increment does not trigger callback

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("icons", partial: "reactions", locals: {room: room})
      end
    end
  end


  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="margin-top: 20px;">
    <%= form.text_field :name %>

    <%= form.submit "Create"%>
  </div>

<% end %>

app/views/rooms/_reactions.html.erb
<%= turbo_frame_tag 'reactions' do %>
  <section id='icons'>
    <%= button_to room_reaction_path(room), method: :post, params: {reaction: :dislike} do %>
      <span class="fa-stack fa-2x">
        <i class="fas fa-square fa-stack-2x"></i>
        <i class="fas fa-angry fa-inverse fa-stack-1x"></i>
        <span class="fa-layers-counter fa-layers-bottom-right fa-2x">
          <%= room.dislikes || 0 %>
        </span>
      </span>
    <% end %>

    <%= button_to room_reaction_path(room), method: :post, params: {reaction: :meh} do %>
      <span class="fa-stack fa-2x">
        <i class="fas fa-square fa-stack-2x"></i>
        <i class="fas fa-meh fa-inverse fa-stack-1x"></i>
        <span class="fa-layers-counter fa-layers-bottom-right fa-2x">
          <%= room.mehs || 0 %>
        </span>
      </span>
    <% end %>

    <%= button_to room_reaction_path(room), method: :post, params: {reaction: :like} do %>
      <span class="fa-stack fa-2x">
        <i class="fas fa-square fa-stack-2x"></i>
        <i class="fas fa-grin fa-inverse fa-stack-1x"></i>
        <span class="fa-layers-counter fa-layers-bottom-right fa-2x">
          <%= room.likes || 0 %>
        </span>
      </span>
    <% end %>

  </section>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

<hr>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<div id="room-head">
  <%= link_to new_room_path, class: "btn", style: "padding-right: 5px;" do %>
    <i class='fas fa-plus'></i> New Retro
  <% end %>
</div>

<div id='room-body'>
  <% @rooms.each do |room| %>
    <div class='room'>
      <%= link_to room, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-red" do %>
        <i class='fas fa-times'></i>
      <% end %>

      <%= link_to edit_room_path(room), class: "btn" do %>
        <i class='fas fa-edit'></i>
      <% end %>

      <%= link_to room.name, room, class: "room-name" %>
    </div>
  <% end %>
</div>

app/views/rooms/new.html.erb
<p></p>
<div id='room-head'>
  <%= link_to rooms_path, class: "btn" do %>
    <i class="fas fa-arrow-circle-left"></i> Back
  <% end %>
</div>


<%= render 'form', room: @room %>

app/views/rooms/show.html.erb
<%= turbo_stream_from @room %>

<section class='title'>
  <h1> <%= @room.name %></h1>
  <%= render partial: "reactions", locals: {room: @room} %>
</section>

<div class='cols-3'>
  <% @room.topics.each do |topic| %>
    <div class='topic'>
      <h2> <%= topic.name %></h2>

      <%= turbo_frame_tag "new_message", src: new_room_topic_message_path(@room, topic), target: "_top" %>

      <div id="<%= topic.snakecase %>">
        <%= render topic.messages %>
      </div>


    </div>

  <% end %>
</div>